server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: "*"        # 暴露所有 Web 端点，含 configprops、env 等
  endpoint:
    health:
      show-details: always  # 便于调试
    configprops:
      enabled: true         # 显式开启（有时默认即开）



monitor:
  user: abcd    #配合代码中的同步修改
  hosts:
    "[20.24.72.150]":
      ip: 20.24.72.150
      units:
        - name: xiaofupo1-manager
          logPath: /app/open/sit/xiaofupo/logs/app.log
          jarPath: /app/open/sit/xiaofupo/
          jarName: xiaofupo-manager
        - name: case1-manager
          logPath: /app/open/sit/case/logs/app.log
          jarPath: /app/open/sit/case/
          jarName: case-manager
        - name: xiaonaigou1-manager
          logPath: /app/open/sit/xiaonaigou/logs/app.log
          jarPath: /app/open/sit/xiaonaigou/
          jarName: xiaonaigou-manager
        - name: dabaigou1-manager
          logPath: /app/open/sit/dabaigou/logs/app.log
          jarPath: /app/open/sit/dabaigou/
          jarName: dabaigou-manager
    "[20.24.72.151]":
      ip: 20.24.72.151
      units:
        - name: xiaofupo2-manager
          logPath: /app/open/sit/xiaofupo/logs/app.log
          jarPath: /app/open/sit/xiaofupo/
          jarName: xiaofupo-manager
        - name: case2-manager
          logPath: /app/open/sit/case/logs/app.log
          jarPath: /app/open/sit/case/
          jarName: case-manager
        - name: xiaonaigou2-manager
          logPath: /app/open/sit/xiaonaigou/logs/app.log
          jarPath: /app/open/sit/xiaonaigou/
          jarName: xiaonaigou-manager
        - name: dabaigou2-manager
          logPath: /app/open/sit/dabaigou/logs/app.log
          jarPath: /app/open/sit/dabaigou/
          jarName: dabaigou-manager