server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: "*"        # 暴露所有 Web 端点，含 configprops、env 等
  endpoint:
    health:
      show-details: always  # 便于调试
    configprops:
      enabled: true         # 显式开启（有时默认即开）


# hosts:
#   "[20.224.105.90]":  # 使用中括号+双引号，这是 Spring Boot 映射 Map Key 的强力写法
#     allowed-units:
#       - uchain-bill-manager
#     allowed-logs:
#       uchain-bill-manager: /app/appoper/sit/bill/logs/app.log
#   "[20.224.105.91]":
#     allowed-units:
#       - uchain-branch-manager

#jumpwatch:
 #ssh-user: appoper
 #cmd-timeout-sec: 15
 #systemd-enabled: true
 #journald-enabled: false
 #command-paths:
 #  systemctl:  /usr/bin/systemctl
 #  journalctl: /usr/bin/journalctl
 #  pgrep:      /usr/bin/pgrep
  # tail:       /usr/bin/tail
monitor:
  user: appoper
  hosts:
    "[20.224.106.90]":
      ip: 20.224.106.90
      units:
        - name: uchain-assetPool-service
          logPath: /app/appoper/sit/assetPool/logs/app.log
          jarPath: /app/appoper/sit/assetPool/
          jarName: uchain-assetPool-service
        - name: uchain-bill-manager
          logPath: /app/appoper/sit/bill/logs/app.log
          jarPath: /app/appoper/sit/bill/
          jarName: uchain-bill-manager
        - name: uchain-loan-manager
          logPath: /app/appoper/sit/loan/logs/app.log
          jarPath: /app/appoper/sit/loan/
          jarName: uchain-loan-manager
        - name: uchain-ticket
          logPath: /app/appoper/sit/ticket/logs/app.log
          jarPath: /app/appoper/sit/ticket/
          jarName: uchain-ticket
    "[20.224.106.91]":
      ip: 20.224.106.91
      units:
        - name: uchain-branch-manager
          logPath: /app/appoper/sit/branch/logs/app.log
          jarPath: /app/appoper/sit/branch/
          jarName: uchain-branch-manager
        - name: uchain-car-manager
          logPath: /app/appoper/sit/car/logs/app.log
          jarPath: /app/appoper/sit/car/
          jarName: uchain-car-manager
        - name: uchain-channel-manager
          logPath: /app/appoper/sit/channel/logs/app.log
          jarPath: /app/appoper/sit/channel/
          jarName: uchain-channel-manager
        - name: uchain-external-manager
          logPath: /app/appoper/sit/external/logs/app.log
          jarPath: /app/appoper/sit/external/
          jarName: uchain-external-manager
    "[20.224.106.92]":
      ip: 20.224.106.92
      units:
        - name: uchain-query-manager
          logPath: /app/appoper/sit/query/logs/app.log
          jarPath: /app/appoper/sit/query/
          jarName: uchain-query-manager
        - name: uchain-order-service
          logPath: /app/appoper/sit/order/logs/app.log
          jarPath: /app/appoper/sit/order/
          jarName: uchain-order-service
        - name: uchain-risk-manager
          logPath: /app/appoper/sit/risk/logs/app.log
          jarPath: /app/appoper/sit/risk/
          jarName: uchain-risk-manager
        - name: uchain-redress-manager
          logPath: /app/appoper/sit/redress/logs/app.log
          jarPath: /app/appoper/sit/redress/
          jarName: uchain-redress-manager
        - name: uchain-batch-manager
          logPath: /app/appoper/sit/batch/logs/app.log
          jarPath: /app/appoper/sit/batch/
          jarName: uchain-batch-manager
    "[20.224.106.93]":
      ip: 20.224.106.93
      units:
        - name: uchain-public-manager
          logPath: /app/appoper/sit/public/logs/app.log
          jarPath: /app/appoper/sit/public/
          jarName: uchain-public-manager
        - name: uchain-loc-service
          logPath: /app/appoper/sit/loc/logs/app.log
          jarPath: /app/appoper/sit/loc/
          jarName: uchain-loc-service
        - name: uchain-customer-manager
          logPath: /app/appoper/sit/customer/logs/app.log
          jarPath: /app/appoper/sit/customer/
          jarName: uchain-customer-manager
        - name: gateway-plugin-uchain
          logPath: /app/appoper/sit/gateway/logs/app.log
          jarPath: /app/appoper/sit/gateway/
          jarName: gateway-plugin-uchain
        - name: uchain-sysbasis-manager
          logPath: /app/appoper/sit/sysbasis/logs/app.log
          jarPath: /app/appoper/sit/sysbasis/
          jarName: uchain-sysbasis-manager
    "[20.224.106.76]":
      ip: 20.224.106.76
      units:
        - name: uchain-carfinance-service
          logPath: /app/appoper/sit/carfinance/logs/app.log
          jarPath: /app/appoper/sit/carfinance/
          jarName: uchain-carfinance-service
        - name: uchain-preposition-manager
          logPath: /app/appoper/sit/preposition/logs/app.log
          jarPath: /app/appoper/sit/preposition/
          jarName: uchain-preposition-manager